### ISSUE TITLE
GetInnerComponent() fails to get InnerComponentReference

### ISSUE THREAD

**Issue by nosenfield** [dmitry-ivashenko/StatefulUI#15]
**Describe the bug**
Outer components report having inner components with specified roles in their list of inner components, but fail to find the item when running `view.GetInnerComponent(role)` 

**To Reproduce**
1. Create a root game object with a StatefulComponent 
2. Create a child game object with a StatefulComponent.
3. Assign a role to the inner StatefulComponent
4. Attempt to access the child via code using `parentStatefulComponent.GetInnerComponent(InnerComponentRole.TheRole)`

**Expected Behavior**
The StatefulComponent should return the inner component with the associated role.

**ScreenShots**
The Unity project screenshot shows the project setup with two StatefulComponents (StatefulComponentRoot, InnerComponent) and the assigned InnerComponentRole of TestComponent. The console output shows:

1. the presence of `InnerComponentRole.TestComponent`
2. one item in the root's InnerComponents list
3. the role of that item which matches `InnerComponentRole.TestComponent`
4. the confirmed presence of that item via `HasInnerComponent()`
5. the null reference returned when getting the inner component using `GetItem<InnerComponentReference>()`
6. the error when `GetInnerComponent()` attempts to access the InnerComponent field on the null reference.

The VSCode screenshot shows the log statements that produce this output.

![Screen Shot 2024-06-26 at 6 50 01 PM](https://github.com/dmitry-ivashenko/StatefulUI/assets/24323176/d6d7c476-23cc-4ae5-8922-2b9acc2db034)
<img width="1158" alt="Screen Shot 2024-06-26 at 6 56 24 PM" src="https://github.com/dmitry-ivashenko/StatefulUI/assets/24323176/ab184fd1-62a8-4c39-8f1e-3d2e16109bc2">

**Versions**
Unity Version 2022.3.6f1
StatefulUI Version 1.0.3

**Comment by dmitry-ivashenko** [comment]
Hey Noah, thank you for your report! Fixed in [1.0.4](https://github.com/dmitry-ivashenko/StatefulUI/releases/tag/release-1.0.4)
