### ISSUE TITLE
view.GetContainer() returns null

### ISSUE THREAD

**Issue by nosenfield** [dmitry-ivashenko/StatefulUI#16]
**Describe the bug**
The view.GetContainer(role) method returns null instead of the existing container

**To Reproduce**
1. Set up a StatefulUI component (`view`) with a ContainerView child and Container role (`MyContainerRole`) for the child.
2. Call `view.HasContainer(ContainerRole.MyContainerRole)` // returns true
3. Call `view.GetContainer(ContainerRole.MyContainerRole)` // returns null

**Expected behavior**
Views return existing containers.

**Screenshots**
![Screen Shot 2024-07-15 at 11 22 40 AM](https://github.com/user-attachments/assets/f4923c38-2397-4d24-abc1-609da041c1a3)
<img width="1110" alt="Screen Shot 2024-07-15 at 11 23 30 AM" src="https://github.com/user-attachments/assets/603943a2-e696-4f86-be1d-d3ed14594733">

**Version Info:**
 - Unity 2022.3.6f1
 - StatefulUI 1.0.4

**Comment by dmitry-ivashenko** [comment]
Hey, thanks for the report. Fixed in [v1.0.5](https://github.com/dmitry-ivashenko/StatefulUI/releases/tag/release-1.0.5)
