### ISSUE TITLE
view.GetObject() returns null

### ISSUE THREAD

**Issue by nosenfield** [dmitry-ivashenko/StatefulUI#18]
**Describe the bug**
The view.GetObject(role) method returns null instead of the existing object

**To Reproduce**

Set up a StatefulUI component (view) with any child object and Object role (MyObjectRole) for the child.
Call view.HasContainer(ObjectRole.MyObjectRole) // returns true
Call view.GetContainer(ObjectRole.MyObjectRole) // returns null

**Expected behavior**
Views return existing object.

**Screenshots**
<img width="1030" alt="Screen Shot 2024-07-27 at 6 02 13 PM" src="https://github.com/user-attachments/assets/ba05facd-9464-4098-a0db-e5e19977daf8">
![Screen Shot 2024-07-27 at 6 02 34 PM](https://github.com/user-attachments/assets/c5eb676f-d4d9-485a-9efe-678eb4f8e4bf)

**Version Info**
- Unity 2022.3.6f1
- StatefulUI 1.0.5

**Comment by dmitry-ivashenko** [comment]
Hey Noah,
Thanks for your report! Please update it to [v1.0.6](https://github.com/dmitry-ivashenko/StatefulUI/releases/tag/release-1.0.6)
