### ISSUE TITLE
'NullReferenceException' when setting an image's sprite value to 'None' in a State description.

### ISSUE THREAD

**Issue by nosenfield** [dmitry-ivashenko/StatefulUI#19]
**Describe the bug**
The StatefulComponent throws a 'NullReferenceException' when you set an image's sprite value to 'None' in a State description.

**To Reproduce**
1. Create a StatefulComponent
2. Add a new State item
3. Add a new state Description item
4. Set the description item Type to "Image"
5. Set the description item Image to any image component
6. Set the description item Impact to "Set Sprite"
7. Set the description item Sprite to "None"

**Expected behavior**
Component should accept "None" as a valid sprite value.

**Screenshots**
<img width="1728" alt="Screen Shot 2024-07-30 at 2 22 09 PM" src="https://github.com/user-attachments/assets/e01ee692-7d5d-4fa1-89cb-30ee28388861">
<img width="1726" alt="Screen Shot 2024-07-30 at 2 22 22 PM" src="https://github.com/user-attachments/assets/7b311211-daad-47e5-9e10-bfa2bff98d62">

**Versions**
Unity 2022.3.6f1
StatefulUI 1.0.6

**Comment by dmitry-ivashenko** [comment]
Thanks for the report! Please try [v1.0.7](https://github.com/dmitry-ivashenko/StatefulUI/releases/tag/release-1.0.7)
