### ISSUE TITLE
StateEditor.cs 40 line causing "ArgumentException: Getting control 1's position..."

### ISSUE THREAD

**Issue by hermer29** [dmitry-ivashenko/StatefulUI#2]
**Describe the bug**

StateEditor.cs 40 line causing "ArgumentException: Getting control 1's position in a group with only 1 controls when doing repaint
Aborting
UnityEngine.GUILayoutGroup.GetNext () (at <82a3a4e0a0a94de5afddd345f6cf50d1>:0)
UnityEngine.GUILayoutUtility.BeginLayoutGroup (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options, System.Type layoutType) (at <82a3a4e0a0a94de5afddd345f6cf50d1>:0)
UnityEditor.EditorGUILayout.BeginVertical (UnityEngine.GUIContent content, UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <da771086bc2e4cfc9ad0a72e083a7f98>:0)
UnityEditor.EditorGUILayout.BeginVertical (UnityEngine.GUIStyle style, UnityEngine.GUILayoutOption[] options) (at <da771086bc2e4cfc9ad0a72e083a7f98>:0)
StatefulUI.Editor.ReferenceInspectors.StateEditor.OnGUI (UnityEngine.Rect rect, UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at Assets/Plugins/StatefulUI/Editor/ReferenceInspectors/StateEditor.cs:40)"

**To Reproduce**
1. Go to StatefulComponent inspector view
2. Open state editor
3. Scroll down to make top of the field is not visible

**Expected behavior**

**Screenshots**
<img width="656" alt="image" src="https://github.com/dmitry-ivashenko/StatefulUI/assets/22891482/b33d92a8-cb2a-4448-a632-1021e2200c93">

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Package Version 1.0.1

**Comment by Niaobu** [comment]
I "solved" this by removing the BeginVertical/EndVertical calls, and I can't seem to notice any difference in the inspector.

**Comment by dmitry-ivashenko** [comment]
> I "solved" this by removing the BeginVertical/EndVertical calls, and I can't seem to notice any difference in the inspector.

You're welcome to make a Pull Request 🙂

**Comment by dmitry-ivashenko** [comment]
Thanks for the report! Please try [v1.0.7](https://github.com/dmitry-ivashenko/StatefulUI/releases/tag/release-1.0.7)
