### ISSUE TITLE
StringBuilder for code generation instead of concatenation

### ISSUE THREAD

**Issue by Ants-Aare** [dmitry-ivashenko/StatefulUI#4]
Hey, I saw your talk on the jetbrains gamedev day, I was speaking directly after you. Was really nice and I like your tool!

But after looking though the repo I saw that you were using a custom implementation of a code generator, mostly using += and string interpolation. I'm not sure if you know about this, but strings are immutable in C#, so doing it this way will duplicate the string every time you add something. Using a builder pattern like you did, means there's like 50 appends to the string, meaning the original string will be duplicated in memory 50 times, each one being longer than the last. Please use a StringBuilder inside the type generator class and do _result.AppendLine() instead of _result +=. Luckily this should be a somewhat easy performance improvement with no bigger ramifications for the code base

**Comment by Amir-Helali** [comment]
Hi @dmitry-ivashenko I'd like to work on this issue.

**Comment by dmitry-ivashenko** [comment]
Hey @Amir-Helali, thanks for your contribution!
