### ISSUE TITLE
[Question] How are you preventing recompilations?

### ISSUE THREAD

**Issue by Ants-Aare** [dmitry-ivashenko/StatefulUI#7]
as I see it you're live modifying c# scripts and adding/removing states, roles etc. If I remember correctly unity has a filesystem watcher and usually updates and recompiles pretty fast on every minute code change. how are you stopping it from doing that? the authoring experience is pretty smooth!

**Comment by dmitry-ivashenko** [comment]
Hey! Sorry for extremely late answer, I broke my github notifications.

I discovered that Unity doesn't react to script modifications while Editor window is focused. All the options in role dropdowns are getting from cache, and when created, the new role also adding to this cache, as you can see in StatefulUI.Runtime.Core.RoleUtils.AddTemporaryRole().

I prefer to disable Auto Refresh completely in my projects (Preferences - General - Auto Refresh) for better experience. Using [toolbar extender](https://github.com/marijnz/unity-toolbar-extender) you can add your own RUN button, which recompile code, open your entry scene and start play mode. I found this way much more convinient.
