### ISSUE TITLE
Add project to OpenUPM or make cleaned up version of just the plugin

### ISSUE THREAD

**Issue by Ants-Aare** [dmitry-ivashenko/StatefulUI#8]
I see that all of the scripts are already in the plugins folder. I'd reccommend to restructure the project so that it can be added with unity package manager or through OpenUPM or as a github submodule. All the Unity project bloat can probably be removed or put into a separate examples/demo repo.
Really good work though!!!

**Comment by Romaleks360** [comment]
+1 on this, would be really nice to see this **awesome** package as, well, a UPM package. Makes the projects much more neat

**Comment by dmitry-ivashenko** [comment]
Thanks to @frutbn now we have UPM support. Cheers 🎉
